# Generated by Django 3.2.25 on 2025-07-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollabApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
